### ISSUE TITLE
Update contribute.md

### ISSUE THREAD

**Issue by BTANISHA11** [OtacilioN/awesome-hacktoberfest#512]
I want to add some sections in contribute.md

1. How to create an issue.
2. How to contribute.
3. How to clone a repositry.
pls assign this to me @OtacilioN

**Comment by Aarize29** [comment]
I have Added Tutorials for that 
please check @OtacilioN

**Comment by weblearner07** [comment]
I could Update contribute.md , Please Assign me this Task.
