### ISSUE TITLE
Add SQL Cheat Sheet

### ISSUE THREAD

**Issue by Debaditya-Som** [OtacilioN/awesome-hacktoberfest#724]
I'd like to suggest that SQL Cheat Sheets be added to this repository's Cheat Sheet section.

**Comment by akshaydubey05** [comment]
@OtacilioN  i have a good SQL cheat sheet i would like to give it to this repo but wll this be counted under hacktoberfest ?

**Comment by Debaditya-Som** [comment]
yes sure bro!
